# Minimal Redis configuration for local deployment
image:
  registry: docker.io
  repository: bitnami/redis
  tag: latest
  pullPolicy: IfNotPresent

auth:
  enabled: false
master:
  persistence:
    enabled: false
replica:
  replicaCount: 0
