destinationRules:
  analysis:
    enabled: true
  api:
    enabled: true
  dashboard:
    enabled: true
gateway:
  name: activity-system-gateway
  namespace: activity-system
  selector:
    istio: ingressgateway
istioInjection:
  enabled: true
metrics:
  enabled: true
  prometheus:
    enabled: true
port:
  name: http
  number: 80
  protocol: HTTP
virtualServices:
  analysis:
    enabled: true
    host: metabob-analysis-api.activity-system.svc.cluster.local
    hostname: api.metabob.local
    metrics:
      enabled: true
      labels:
        service: analysis-api
    port: 8080
  api:
    enabled: true
    host: metabob-activity-api.activity-system.svc.cluster.local
    hostname: api.minibob.local
    metrics:
      enabled: true
      labels:
        service: api
    port: 8080
  dashboard:
    enabled: true
    host: activity-dashboard.activity-system.svc.cluster.local
    hostname: dashboard.minibob.local
    metrics:
      enabled: true
      labels:
        service: dashboard
    port: 3000
  devbob:
    enabled: true
    host: minibob-devbob.activity-system.svc.cluster.local
    hostname: devbob.minibob.local
    metrics:
      enabled: true
      labels:
        service: devbob
    port: 8080
