#!/bin/bash
# Document the boredom-manager template mapping fix

echo "Annotation: BoredomManager now maps activity types to meta-templates"
echo ""
echo "Component: executeBoredomActivity()"
echo "File: repos/metabob-opencode/packages/opencode/src/session/boredom-manager.ts:254-396"
echo ""
echo "Fix Applied:"
echo "  - Map 'improve-template' → 'evolve-activity-self-contained'"
echo "  - Map 'debug-failures' → 'debug-activity-self-contained'"
echo "  - Map 'optimize-performance' → 'optimize-activity-self-contained' (TODO)"
echo ""
echo "Reason:"
echo "  Previously, boredom system executed stale templates directly (e.g., if backend"
echo "  said 'improve template X', it would execute template X, not the evolve-activity"
echo "  meta-template). This broke the self-improvement loop because stale templates"
echo "  were never actually improved."
echo ""
echo "Impact:"
echo "  - Boredom system now correctly improves templates via meta-templates"
echo "  - Templates with low success rates will be automatically evolved"
echo "  - Templates with high failure rates will be automatically debugged"
echo "  - Self-improvement loop is now functional"
