#!/bin/bash
# gen-env.sh — write /etc/substrate/env from container environment variables.
# Sourced by every systemd unit via EnvironmentFile=/etc/substrate/env.
#
# Only ANTHROPIC_API_KEY is required from the operator.
# JWT_SECRET and SURREAL_PASS are generated internally if not provided.
# METABOB_API_KEY is a bootstrap value replaced by identity-vessel after seeding.
set -euo pipefail

: "${ANTHROPIC_API_KEY:?ANTHROPIC_API_KEY is required — the only operator-side credential}"

# Internal secrets: auto-generate if not provided.
# These are substrate-internal and never need to come from outside.
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
SURREAL_PASS="${SURREAL_PASS:-$(openssl rand -hex 16)}"

# Bootstrap key: used only for the initial identity-vessel signup call.
# After seed-identity.ts runs, vessels use the HMAC keys it issues.
# Stored in /workspace/.substrate-secrets so restarts reuse the same value.
if [[ -z "${METABOB_API_KEY:-}" ]]; then
  SECRETS_FILE="/workspace/.substrate-secrets"
  if [[ -f "$SECRETS_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$SECRETS_FILE"
  fi
  METABOB_API_KEY="${METABOB_API_KEY:-$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 32)}"
fi

# Optional per-vessel keys — fall back to METABOB_API_KEY if unset (D4)
LOCAL_TOOLS_VESSEL_API_KEY="${LOCAL_TOOLS_VESSEL_API_KEY:-${METABOB_API_KEY}}"
GOAL_HOST_VESSEL_API_KEY="${GOAL_HOST_VESSEL_API_KEY:-${METABOB_API_KEY}}"
RIBOSOME_VESSEL_API_KEY="${RIBOSOME_VESSEL_API_KEY:-${METABOB_API_KEY}}"
CONCEPT_DB_API_KEY="${CONCEPT_DB_API_KEY:-${METABOB_API_KEY}}"

mkdir -p /workspace
cat > /etc/substrate/env <<EOF
# Generated by gen-env.sh — do not edit manually
JWT_SECRET=${JWT_SECRET}
SURREAL_PASS=${SURREAL_PASS}
METABOB_API_KEY=${METABOB_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
LOCAL_TOOLS_VESSEL_API_KEY=${LOCAL_TOOLS_VESSEL_API_KEY}
GOAL_HOST_VESSEL_API_KEY=${GOAL_HOST_VESSEL_API_KEY}
RIBOSOME_VESSEL_API_KEY=${RIBOSOME_VESSEL_API_KEY}
CONCEPT_DB_API_KEY=${CONCEPT_DB_API_KEY}

# Substrate internal: allow all localhost calls to bypass identity-vessel rate limiting
RATE_LIMIT_ALLOWLIST_IPS=127.0.0.1,unknown

# Infrastructure
SURREALDB_URL=http://127.0.0.1:8000
SURREALDB_NAMESPACE=activity-system
SURREALDB_DATABASE=learning_loop
SURREALDB_USERNAME=root
SURREALDB_PASSWORD=${SURREAL_PASS}
REDIS_URL=redis://127.0.0.1:6379

# Vessel endpoints (all localhost)
DISCOVERY_ENDPOINT=http://127.0.0.1:8100
METABOB_ENDPOINT=http://127.0.0.1:8080
ACTIVITY_API_ENDPOINT=http://127.0.0.1:8080
IDENTITY_VESSEL_URL=http://127.0.0.1:8101
IDENTITY_ENDPOINT=http://127.0.0.1:8101

# Dense search (F-V58 fix — must point to directory containing model.onnx + vocab.txt)
EMBEDDING_MODEL_DIR=/vessels/activity-api/src/assets/models/all-MiniLM-L6-v2
EOF

chmod 600 /etc/substrate/env
echo "[gen-env] wrote /etc/substrate/env"

# Persist generated secrets to workspace so restarts reuse the same values.
# This file is bind-mounted from the host at /workspace.
cat > /workspace/.substrate-secrets <<SECRETS
# Substrate internal secrets — auto-generated on first run, reused on restart.
# DO NOT commit this file. Add workspace/.substrate-secrets to .gitignore.
JWT_SECRET=${JWT_SECRET}
SURREAL_PASS=${SURREAL_PASS}
METABOB_API_KEY=${METABOB_API_KEY}
SECRETS
chmod 600 /workspace/.substrate-secrets
echo "[gen-env] persisted secrets to /workspace/.substrate-secrets"
