#!/bin/bash
# gen-env.sh — write /etc/substrate/env from container environment variables.
# Sourced by every systemd unit via EnvironmentFile=/etc/substrate/env.
#
# LLM provider — at least one key must be set:
#   ANTHROPIC_API_KEY   — Anthropic Claude (default / preferred)
#   OPENAI_API_KEY      — OpenAI-compatible (OpenAI, Ollama, Groq, Together, vLLM, …)
#   OPENAI_BASE_URL     — override base URL for non-OpenAI endpoints (optional)
#   LLM_DEFAULT_MODEL   — override default model (optional; defaults to claude-sonnet-4-6)
#
# JWT_SECRET and SURREAL_PASS are generated internally if not provided.
# METABOB_API_KEY is a bootstrap value replaced by identity-vessel after seeding.
set -euo pipefail

if [[ -z "${ANTHROPIC_API_KEY:-}" && -z "${OPENAI_API_KEY:-}" ]]; then
  echo "[gen-env] ERROR: No LLM provider key found. Set ANTHROPIC_API_KEY or OPENAI_API_KEY." >&2
  exit 1
fi

# Internal secrets: auto-generate if not provided.
# These are substrate-internal and never need to come from outside.
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
SURREAL_PASS="${SURREAL_PASS:-$(openssl rand -hex 16)}"

# Bootstrap key: used only for the initial identity-vessel signup call.
# After seed-identity.ts runs, vessels use the HMAC keys it issues.
# Stored in /workspace/.substrate-secrets so restarts reuse the same value.
if [[ -z "${METABOB_API_KEY:-}" ]]; then
  SECRETS_FILE="/workspace/.substrate-secrets"
  if [[ -f "$SECRETS_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$SECRETS_FILE"
  fi
  METABOB_API_KEY="${METABOB_API_KEY:-$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 32)}"
fi

# Optional per-vessel keys — fall back to METABOB_API_KEY if unset (D4)
LOCAL_TOOLS_VESSEL_API_KEY="${LOCAL_TOOLS_VESSEL_API_KEY:-${METABOB_API_KEY}}"
GOAL_HOST_VESSEL_API_KEY="${GOAL_HOST_VESSEL_API_KEY:-${METABOB_API_KEY}}"
RIBOSOME_VESSEL_API_KEY="${RIBOSOME_VESSEL_API_KEY:-${METABOB_API_KEY}}"
CONCEPT_DB_API_KEY="${CONCEPT_DB_API_KEY:-${METABOB_API_KEY}}"

# Self-development push credential (container-side direct push to AviGopal repos).
# Fine-grained PAT (Contents:R/W). Comes from the environment (compose/run) or
# the persisted secrets file; reused across restarts. Empty = self-push disabled.
# NB: this block (and the persisted-secrets heredoc below) must round-trip the
# PAT, else gen-env would wipe an operator-supplied PAT on the next restart.
if [[ -z "${SUBSTRATE_GIT_PAT:-}" && -f /workspace/.substrate-secrets ]]; then
  # shellcheck disable=SC1091
  source /workspace/.substrate-secrets
fi
SUBSTRATE_GIT_PAT="${SUBSTRATE_GIT_PAT:-}"
SUBSTRATE_GIT_AUTHOR_NAME="${SUBSTRATE_GIT_AUTHOR_NAME:-Substrate Autonomous}"
SUBSTRATE_GIT_AUTHOR_EMAIL="${SUBSTRATE_GIT_AUTHOR_EMAIL:-substrate-autonomous@metabob.com}"

mkdir -p /workspace
cat > /etc/substrate/env <<EOF
# Generated by gen-env.sh — do not edit manually
# Values are double-quoted so entries containing spaces (e.g. the git author
# name "Substrate Autonomous") source cleanly via `set -a && . /etc/substrate/env`.
# Unquoted, `SUBSTRATE_GIT_AUTHOR_NAME=Substrate Autonomous` runs `Autonomous`
# as a command ("command not found") and mis-sets the author to just "Substrate".
JWT_SECRET="${JWT_SECRET}"
SURREAL_PASS="${SURREAL_PASS}"
METABOB_API_KEY="${METABOB_API_KEY}"
# LLM provider credentials — at least one must be non-empty (validated above).
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
OPENAI_BASE_URL="${OPENAI_BASE_URL:-}"
LLM_DEFAULT_MODEL="${LLM_DEFAULT_MODEL:-}"
# Substrate root inside the container = the bind-mounted host repo path
# (docker run -v \$(REPO_ROOT):\$(REPO_ROOT):ro, passed in via -e SUBSTRATE_ROOT).
# Every tick unit references its script as \${SUBSTRATE_ROOT}/scripts/substrate/...
# so the fleet is relocatable: rename/move the repo and re-run \`make run-live\`
# and nothing in the units changes. Empty here means SUBSTRATE_ROOT was not
# passed — units will fail loudly rather than read a stale hardcoded path.
SUBSTRATE_ROOT="${SUBSTRATE_ROOT:-}"
# Writable run-dir for the timer SCRIPTS (self-activation, 2026-06-26). The tick
# units' run-dir.conf drop-ins reference their script as
# \${SUBSTRATE_RUN_DIR}/<name>.ts. substrate-active-scripts-seed.service copies
# the (boot-fresh, read-only) bind scripts into this writable volume dir at boot;
# the development-vessel activate_substrate_script resolver then overwrites a copy
# in place to make a substrate-authored new version live on the NEXT timer firing,
# with NO container restart. Defaulted here so a recreate is self-activation-capable
# even if the value wasn't passed in.
SUBSTRATE_RUN_DIR="${SUBSTRATE_RUN_DIR:-/workspace/active-scripts}"
GITHUB_TOKEN="${GITHUB_TOKEN:-}"
SUBSTRATE_GIT_PAT="${SUBSTRATE_GIT_PAT}"
SUBSTRATE_GIT_AUTHOR_NAME="${SUBSTRATE_GIT_AUTHOR_NAME}"
SUBSTRATE_GIT_AUTHOR_EMAIL="${SUBSTRATE_GIT_AUTHOR_EMAIL}"

# Self-alteration cutover: direct-push mode. With the writable vessel clones
# (setup-git-push.sh) + SUBSTRATE_GIT_PAT credential helper in place, the
# vessel-mitosis-cutover resolver commits+pushes the authored change to
# origin/dev of the vessel clone, then mirrors the staged files into the live
# /vessels/<vessel> runtime and restarts the unit. Without these three knobs
# the cutover falls back to host-sync-intent mode (which no-ops here, since the
# host repo bind mount is read-only) — i.e. authored fixes never land.
#   MITOSIS_DIRECT_PUSH=1        — enable commit+push+mirror instead of intent
#   MITOSIS_RUNTIME_DIR=/vessels — live runtime: also the freshness-check root,
#                                  so the gate hashes the same file apply-proposal
#                                  patched (kills the base_sha path-mismatch livelock)
#   MITOSIS_PUSH_CLONE_DIR       — where setup-git-push put the per-vessel clones
MITOSIS_DIRECT_PUSH=${MITOSIS_DIRECT_PUSH:-1}
MITOSIS_RUNTIME_DIR=${MITOSIS_RUNTIME_DIR:-/vessels}
MITOSIS_PUSH_CLONE_DIR=${MITOSIS_PUSH_CLONE_DIR:-/workspace/git/vessels}
LOCAL_TOOLS_VESSEL_API_KEY=${LOCAL_TOOLS_VESSEL_API_KEY}
GOAL_HOST_VESSEL_API_KEY=${GOAL_HOST_VESSEL_API_KEY}
RIBOSOME_VESSEL_API_KEY=${RIBOSOME_VESSEL_API_KEY}
CONCEPT_DB_API_KEY=${CONCEPT_DB_API_KEY}

# Substrate internal: allow all localhost calls to bypass identity-vessel rate limiting
RATE_LIMIT_ALLOWLIST_IPS=127.0.0.1,unknown

# Infrastructure
SURREALDB_URL=http://127.0.0.1:8000
SURREALDB_NAMESPACE=activity-system
SURREALDB_DATABASE=learning_loop
SURREALDB_USERNAME=root
SURREALDB_PASSWORD=${SURREAL_PASS}
REDIS_URL=redis://127.0.0.1:6379

# Vessel endpoints (all localhost)
DISCOVERY_ENDPOINT=http://127.0.0.1:8100
METABOB_ENDPOINT=http://127.0.0.1:8080
ACTIVITY_API_ENDPOINT=http://127.0.0.1:8080
IDENTITY_VESSEL_URL=http://127.0.0.1:8101
IDENTITY_ENDPOINT=http://127.0.0.1:8101

# Dense search (F-V58 fix — must point to directory containing model.onnx + vocab.txt)
EMBEDDING_MODEL_DIR=/vessels/activity-api/src/assets/models/all-MiniLM-L6-v2

# M1 embedding-conditioned Thompson prior (concept_vugylIHzIMvk).
# When true, posterior-update.ts looks up per-cell embeddings from concept-db
# and routes prior seeding through computeEmbeddingConditionedPrior. Falls
# back to the concept-neighbor empirical-Bayes path on any miss.
EMBEDDING_PRIOR_ENABLED=true

# M1 continuous-training observer (concept_KKwxHmPfEMSY). Opt-in: when true,
# activity-api spawns an in-process broadcaster subscriber that buffers
# eligible (variant, signature) cells from task.completed events and re-fits
# θ_α/θ_β into embedding_prior_weights on count or time threshold. Default
# off — Layer 1 (systemd m1-trainer.timer) handles the periodic re-fit; turn
# this on for sub-15min responsiveness once it's been load-tested.
EMBEDDING_PRIOR_OBSERVER_ENABLED=false

# Trace-retention sweep (src/services/trace-retention.ts). Bounds the
# activity_execution_traces store so the lifecycle flooders (validator-dispatch,
# slot-binding) don't re-bloat it past ~100K rows (the O(rows) trace-read hot
# path gates the learning loop). Keeps ALL traces < 2h old plus a uniform-random
# 2000-row sample of each cold (activity_id,status) stratum; deletes in bounded
# 1000-row batches every 30min. Reviewed via dry-run 2026-06-21 before enabling
# (one-off sweep removed 108,564 rows: 265K->160K, CPU flat throughout).
TRACE_RETENTION_ENABLED=true
TRACE_RETENTION_DRY_RUN=false

# Obsidian plugin endpoint (2026-06-22). The obsidian-vessel plugin runs IN the
# single-container substrate (obsidian-desktop.service) and serves on
# 127.0.0.1:27182. The obsidian resolvers (behavior-scan, reflect, deliver-assist,
# verify-output, request-scan, feedback-scan) default to host.docker.internal:27183
# — a leftover from when Obsidian ran on the operator's HOST — which is DOWN here,
# so the operator-modeling + assist loop was silently starved (modeled:0). Point
# them at the live in-container plugin so the feedback loop can actually read events
# and write back.
OBSIDIAN_PLUGIN_ENDPOINT=http://127.0.0.1:27182
EOF

chmod 600 /etc/substrate/env
echo "[gen-env] wrote /etc/substrate/env"

# Pass through vessel-subset selection + fork owner so units (setup-git-push) and
# apply-inventory read them from the EnvironmentFile. Absent vars stay absent
# (apply-inventory defaults to "keep everything").
{
  echo "SUBSTRATE_REPO_OWNER=${SUBSTRATE_REPO_OWNER:-AviGopal}"
  [ -n "${ENABLED_ROLES:-}" ]       && echo "ENABLED_ROLES=${ENABLED_ROLES}"
  [ -n "${ENABLED_VESSELS:-}" ]     && echo "ENABLED_VESSELS=${ENABLED_VESSELS}"
  [ -n "${DISABLED_VESSELS:-}" ]    && echo "DISABLED_VESSELS=${DISABLED_VESSELS}"
  [ -n "${SUBSTRATE_BIND_HOST:-}" ] && echo "SUBSTRATE_BIND_HOST=${SUBSTRATE_BIND_HOST}"
} >> /etc/substrate/env

# Persist generated secrets to workspace so restarts reuse the same values.
# This file is bind-mounted from the host at /workspace.
cat > /workspace/.substrate-secrets <<SECRETS
# Substrate internal secrets — auto-generated on first run, reused on restart.
# DO NOT commit this file. Add workspace/.substrate-secrets to .gitignore.
JWT_SECRET=${JWT_SECRET}
SURREAL_PASS=${SURREAL_PASS}
METABOB_API_KEY=${METABOB_API_KEY}
SUBSTRATE_GIT_PAT=${SUBSTRATE_GIT_PAT}
SECRETS
chmod 600 /workspace/.substrate-secrets
echo "[gen-env] persisted secrets to /workspace/.substrate-secrets"
