#!/bin/bash
# gen-env.sh — write /etc/substrate/env from container environment variables.
# Sourced by every systemd unit via EnvironmentFile=/etc/substrate/env.
set -euo pipefail

: "${JWT_SECRET:?JWT_SECRET is required}"
: "${SURREAL_PASS:?SURREAL_PASS is required}"
: "${METABOB_API_KEY:?METABOB_API_KEY is required}"
: "${ANTHROPIC_API_KEY:?ANTHROPIC_API_KEY is required}"

cat > /etc/substrate/env <<EOF
# Generated by gen-env.sh — do not edit manually
JWT_SECRET=${JWT_SECRET}
SURREAL_PASS=${SURREAL_PASS}
METABOB_API_KEY=${METABOB_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Infrastructure
SURREALDB_URL=http://127.0.0.1:8000
SURREALDB_NAMESPACE=activity-system
SURREALDB_DATABASE=learning_loop
SURREALDB_USERNAME=root
SURREALDB_PASSWORD=${SURREAL_PASS}
REDIS_URL=redis://127.0.0.1:6379

# Vessel endpoints (all localhost)
DISCOVERY_ENDPOINT=http://127.0.0.1:8100
METABOB_ENDPOINT=http://127.0.0.1:8080
ACTIVITY_API_ENDPOINT=http://127.0.0.1:8080
IDENTITY_VESSEL_URL=http://127.0.0.1:8101

# Vessel identities
VESSEL_ID=substrate-local
EOF

chmod 600 /etc/substrate/env
echo "[gen-env] wrote /etc/substrate/env"
