apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metabob-activity-api.fullname" . }}
  labels:
    {{- include "metabob-activity-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  surrealdb-username: {{ .Values.config.surrealdb.username | quote }}
  surrealdb-password: {{ .Values.config.surrealdb.password | quote }}
