{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: surrealdb-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | default "root" | quote }}
  password: {{ .Values.auth.password | default "changeme" | quote }}
{{- end }}

