#!/usr/bin/env bash
#
# minibob-pr.sh - Execute MiniBob and create a PR
#
# Usage:
#   ./minibob-pr.sh "Your goal here"
#   ./minibob-pr.sh --issue 123
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
info() { echo -e "${BLUE}ℹ${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
error() { echo -e "${RED}✗${NC} $1"; exit 1; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }

usage() {
  cat <<EOF
Usage: $0 [OPTIONS] "goal"

Execute MiniBob with a goal and create a PR for the changes.

OPTIONS:
  --issue NUM     Work on specific issue number
  --base BRANCH   Base branch for PR (default: main)
  --draft         Create as draft PR
  --help          Show this help

EXAMPLES:
  # Execute a goal and create PR
  $0 "Fix the authentication bug"

  # Work on a specific issue
  $0 --issue 123

  # Create draft PR
  $0 --draft "Add new feature"

  # Use different base branch
  $0 --base dev "Fix linting errors"

ENVIRONMENT:
  ANTHROPIC_API_KEY    - Required for MiniBob LLM
  METABOB_API_KEY      - Required for activity backend
  ACTIVITY_API_ENDPOINT - Activity API URL (default: https://activity.metabob.com)
EOF
  exit 0
}

# Parse arguments
ISSUE_NUM=""
BASE_BRANCH="main"
DRAFT_FLAG=""
GOAL=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --issue)
      ISSUE_NUM="$2"
      shift 2
      ;;
    --base)
      BASE_BRANCH="$2"
      shift 2
      ;;
    --draft)
      DRAFT_FLAG="--draft"
      shift
      ;;
    --help)
      usage
      ;;
    *)
      GOAL="$1"
      shift
      ;;
  esac
done

# Validation
if [ -z "$GOAL" ] && [ -z "$ISSUE_NUM" ]; then
  error "Either provide a goal or specify --issue NUM"
fi

if ! command -v gh &> /dev/null; then
  error "GitHub CLI (gh) is required. Install: https://cli.github.com/"
fi

if ! command -v minibob &> /dev/null; then
  error "MiniBob is required. Install: bun add -g @metabob/minibob@latest"
fi

# Check for required environment variables
: "${ACTIVITY_API_ENDPOINT:=https://activity.metabob.com}"

if [ -z "$ANTHROPIC_API_KEY" ] && [ -z "$METABOB_API_KEY" ]; then
  warn "Missing API keys. MiniBob may fail without ANTHROPIC_API_KEY or METABOB_API_KEY"
fi

# Get issue details if working on an issue
if [ -n "$ISSUE_NUM" ]; then
  info "Fetching issue #$ISSUE_NUM..."

  ISSUE_TITLE=$(gh issue view "$ISSUE_NUM" --json title --jq '.title') || error "Failed to fetch issue #$ISSUE_NUM"
  ISSUE_BODY=$(gh issue view "$ISSUE_NUM" --json body --jq '.body')

  GOAL="$ISSUE_TITLE"
  if [ -n "$ISSUE_BODY" ]; then
    GOAL="$GOAL

$ISSUE_BODY"
  fi

  success "Working on issue #$ISSUE_NUM: $ISSUE_TITLE"
fi

# Check for clean working tree
if ! git diff --quiet || ! git diff --cached --quiet; then
  error "Working tree is not clean. Commit or stash changes first."
fi

# Get current branch
CURRENT_BRANCH=$(git branch --show-current)
info "Current branch: $CURRENT_BRANCH"

# Create new branch
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
if [ -n "$ISSUE_NUM" ]; then
  NEW_BRANCH="minibob/issue-$ISSUE_NUM-$TIMESTAMP"
else
  NEW_BRANCH="minibob/local-$TIMESTAMP"
fi

info "Creating branch: $NEW_BRANCH"
git checkout -b "$NEW_BRANCH" || error "Failed to create branch"

# Execute MiniBob
info "Executing MiniBob..."
echo "Goal: $GOAL"
echo ""

if minibob --single "$GOAL"; then
  EXIT_CODE=0
  success "MiniBob execution completed successfully"
else
  EXIT_CODE=$?
  warn "MiniBob execution failed with exit code: $EXIT_CODE"
fi

# Check for changes
if git diff --quiet && git diff --cached --quiet; then
  warn "No changes made by MiniBob"
  info "Cleaning up branch..."
  git checkout "$CURRENT_BRANCH"
  git branch -D "$NEW_BRANCH"
  exit 0
fi

# Show changes
info "Changes made:"
git status --short

# Commit changes
info "Committing changes..."
git add -A

if [ -n "$ISSUE_NUM" ]; then
  COMMIT_MSG="fix: resolve issue #$ISSUE_NUM

$ISSUE_TITLE

Exit code: $EXIT_CODE
Execution trace: $ACTIVITY_API_ENDPOINT/traces/

Closes #$ISSUE_NUM

Co-Authored-By: MiniBob <minibob@metabob.com>"
else
  COMMIT_MSG="feat: $GOAL

Exit code: $EXIT_CODE
Execution trace: $ACTIVITY_API_ENDPOINT/traces/

Co-Authored-By: MiniBob <minibob@metabob.com>"
fi

git commit -m "$COMMIT_MSG" || error "Failed to commit changes"
success "Changes committed"

# Push branch
info "Pushing branch to remote..."
git push origin "$NEW_BRANCH" || error "Failed to push branch"
success "Branch pushed"

# Create PR
info "Creating pull request..."

if [ -n "$ISSUE_NUM" ]; then
  PR_TITLE="Fix: $ISSUE_TITLE"
  PR_BODY="## Summary
Resolves #$ISSUE_NUM

## Changes
Automated fix generated by MiniBob based on issue description.

## Execution Details
- **Exit Code**: $EXIT_CODE
- **Branch**: \`$NEW_BRANCH\`
- **Execution Trace**: $ACTIVITY_API_ENDPOINT/traces/
- **Executed From**: Local host

## Testing
- [ ] CI checks passing
- [ ] Manual review completed (if needed)

---
🤖 Generated by [MiniBob](https://github.com/metabobproject/minibob) from local execution

Closes #$ISSUE_NUM"
else
  PR_TITLE="$GOAL"
  PR_BODY="## Summary
$GOAL

## Changes
Changes generated by MiniBob execution.

## Execution Details
- **Exit Code**: $EXIT_CODE
- **Branch**: \`$NEW_BRANCH\`
- **Execution Trace**: $ACTIVITY_API_ENDPOINT/traces/
- **Executed From**: Local host

## Testing
- [ ] CI checks passing
- [ ] Manual review completed (if needed)

---
🤖 Generated by [MiniBob](https://github.com/metabobproject/minibob) from local execution"
fi

PR_URL=$(gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --base "$BASE_BRANCH" \
  --head "$NEW_BRANCH" \
  --label "minibob,automated" \
  $DRAFT_FLAG) || error "Failed to create PR"

success "Pull request created: $PR_URL"

# Comment on issue if applicable
if [ -n "$ISSUE_NUM" ]; then
  info "Commenting on issue #$ISSUE_NUM..."
  gh issue comment "$ISSUE_NUM" --body "✅ **MiniBob execution completed from local host!**

PR created: $PR_URL

The PR will be automatically merged once all checks pass." || warn "Failed to comment on issue"
fi

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
success "MiniBob PR workflow completed!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Branch:      $NEW_BRANCH"
echo "Base:        $BASE_BRANCH"
echo "PR:          $PR_URL"
if [ -n "$ISSUE_NUM" ]; then
  echo "Issue:       #$ISSUE_NUM"
fi
echo "Exit Code:   $EXIT_CODE"
echo ""
info "Monitor CI checks: gh pr checks $PR_URL"
info "View PR: gh pr view $PR_URL"
echo ""
info "The PR will be auto-merged once all checks pass."
echo ""
