#!/bin/bash
# =============================================================================
# DevBob Quick Start
# =============================================================================
# Interactive setup script for first-time DevBob users
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[!]${NC} $1"; }
log_error() { echo -e "${RED}[✗]${NC} $1"; }
log_step() { echo -e "${CYAN}[STEP]${NC} $1"; }

clear
cat << "EOF"
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║            Welcome to DevBob Quick Start!                ║
║                                                           ║
║   AI Agents for Multi-Repository Development             ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝

EOF

echo ""
log_info "This script will help you set up DevBob in a few minutes."
echo ""

# Step 1: Prerequisites Check
log_step "1/5 - Checking Prerequisites"
echo ""

MISSING_DEPS=()

if ! command -v docker &> /dev/null; then
    MISSING_DEPS+=("docker")
fi

if ! command -v docker-compose &> /dev/null; then
    MISSING_DEPS+=("docker-compose")
fi

if ! command -v bun &> /dev/null; then
    MISSING_DEPS+=("bun")
fi

if ! command -v ssh &> /dev/null; then
    MISSING_DEPS+=("ssh")
fi

if [ ${#MISSING_DEPS[@]} -gt 0 ]; then
    log_error "Missing required dependencies:"
    for dep in "${MISSING_DEPS[@]}"; do
        echo "  - $dep"
    done
    echo ""
    log_info "Please install missing dependencies and try again."
    exit 1
fi

log_success "All prerequisites installed"
echo ""

# Step 2: Check OpenCode Binaries
log_step "2/5 - Checking OpenCode Binaries"
echo ""

if [ ! -d "$PROJECT_ROOT/repos/metabob-opencode/packages/opencode/dist/opencode-linux-x64" ]; then
    log_warn "OpenCode binaries not found. Building now..."
    log_info "This will take ~5 minutes..."
    echo ""
    
    cd "$PROJECT_ROOT/repos/metabob-opencode"
    
    log_info "Installing dependencies..."
    bun install --no-optional > /dev/null 2>&1 || {
        log_error "Failed to install dependencies"
        exit 1
    }
    
    cd packages/opencode
    log_info "Building binaries..."
    bun run build || {
        log_error "Failed to build OpenCode"
        exit 1
    }
    
    log_success "OpenCode binaries built successfully"
else
    log_success "OpenCode binaries found"
fi
echo ""

# Step 3: Configure Environment
log_step "3/5 - Configuring Environment"
echo ""

ENV_FILE="$PROJECT_ROOT/configs/.env.devbob.local"

if [ -f "$ENV_FILE" ]; then
    log_warn "Configuration already exists at:"
    echo "  $ENV_FILE"
    echo ""
    read -p "Overwrite existing configuration? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Keeping existing configuration"
        SKIP_CONFIG=true
    fi
fi

if [ "$SKIP_CONFIG" != "true" ]; then
    log_info "Setting up configuration..."
    echo ""
    
    # API Key
    echo "Enter your Anthropic API key:"
    echo "(Get one from: https://console.anthropic.com/)"
    read -p "API Key: " ANTHROPIC_KEY
    
    if [ -z "$ANTHROPIC_KEY" ]; then
        log_error "API key is required"
        exit 1
    fi
    
    echo ""
    
    # Git repository URLs
    log_info "Configure git repositories (or press Enter to use defaults):"
    echo ""
    
    read -p "OpenCode Repository URL [git@github.com:metabobproject/opencode.git]: " OPENCODE_REPO
    OPENCODE_REPO=${OPENCODE_REPO:-git@github.com:metabobproject/opencode.git}
    
    read -p "OpenCode Branch [main]: " OPENCODE_BRANCH
    OPENCODE_BRANCH=${OPENCODE_BRANCH:-main}
    
    echo ""
    
    # Create configuration
    cat > "$ENV_FILE" << CONFIG_EOF
# =============================================================================
# DevBob Configuration (Generated by quick-start.sh)
# =============================================================================

# LLM API Keys
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
OPENAI_API_KEY=

# Git Repositories
DEVBOB_OPENCODE_REPO=$OPENCODE_REPO
DEVBOB_OPENCODE_BRANCH=$OPENCODE_BRANCH

# You can add more repositories here:
# DEVBOB_CLI_REPO=git@github.com:org/metabob-cli.git
# DEVBOB_CLI_BRANCH=main
# DEVBOB_RPC_API_REPO=git@github.com:org/metabob-rpc-api.git
# DEVBOB_RPC_API_BRANCH=main

# Git Behavior
DEVBOB_CHECKOUT_MODE=shallow
DEVBOB_REPO_DEPTH=1
DEVBOB_AUTO_PUSH=false
DEVBOB_PUSH_ON_EXIT=true

# SSH Keys
SSH_KEY_DIR=~/.ssh

# Backend (optional)
METABOB_API_URL=
METABOB_API_KEY=
METABOB_PROJECT_ID=devbob-project
WAIT_FOR_BACKEND=false

# Logging
LOG_LEVEL=INFO
CONFIG_EOF
    
    log_success "Configuration created at: $ENV_FILE"
fi
echo ""

# Step 4: Build Docker Image
log_step "4/5 - Building Docker Image"
echo ""

if docker images devbob:latest | grep -q devbob; then
    log_success "DevBob image already exists"
    echo ""
    read -p "Rebuild image? (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        REBUILD=true
    fi
else
    REBUILD=true
fi

if [ "$REBUILD" = "true" ]; then
    log_info "Building DevBob image (~10 minutes)..."
    "$SCRIPT_DIR/build-devbob.sh" || {
        log_error "Failed to build Docker image"
        exit 1
    }
    log_success "Docker image built successfully"
else
    log_info "Skipping image build"
fi
echo ""

# Step 5: Start Containers
log_step "5/5 - Starting DevBob Containers"
echo ""

log_info "Which containers would you like to start?"
echo ""
echo "  1) OpenCode only (recommended for first time)"
echo "  2) OpenCode + CLI"
echo "  3) All containers (OpenCode, CLI, RPC API)"
echo ""
read -p "Choice [1]: " CONTAINER_CHOICE
CONTAINER_CHOICE=${CONTAINER_CHOICE:-1}

case $CONTAINER_CHOICE in
    1)
        CONTAINERS="devbob-opencode"
        ;;
    2)
        CONTAINERS="devbob-opencode devbob-cli"
        ;;
    3)
        CONTAINERS="devbob-opencode devbob-cli devbob-rpc-api"
        ;;
    *)
        log_error "Invalid choice"
        exit 1
        ;;
esac

echo ""
log_info "Starting containers: $CONTAINERS"
echo ""

cd "$PROJECT_ROOT/configs"
docker-compose -f docker-compose.devbob.yaml --env-file .env.devbob.local up -d $CONTAINERS || {
    log_error "Failed to start containers"
    exit 1
}

echo ""
log_success "Containers started successfully!"
echo ""

# Wait for health checks
log_info "Waiting for containers to be ready..."
sleep 10

# Show status
echo ""
log_info "Container Status:"
echo ""
docker-compose -f docker-compose.devbob.yaml ps

echo ""
log_success "✨ DevBob is ready!"
echo ""

# Show next steps
cat << NEXT_STEPS
╔═══════════════════════════════════════════════════════════╗
║                     Next Steps                            ║
╚═══════════════════════════════════════════════════════════╝

1. Check logs:
   docker-compose -f configs/docker-compose.devbob.yaml logs -f

2. Test ACP connection:
   curl http://localhost:3004/acp/sessions

3. Send a task (example):
   curl -X POST http://localhost:3004/acp/sessions \\
     -H "Content-Type: application/json" \\
     -d '{"prompt": "Add unit tests for authentication"}'

4. View comprehensive guide:
   cat BOOTSTRAP_GUIDE.md

5. Stop containers:
   docker-compose -f configs/docker-compose.devbob.yaml down

╔═══════════════════════════════════════════════════════════╗
║                 Happy Coding with DevBob! 🚀              ║
╚═══════════════════════════════════════════════════════════╝

NEXT_STEPS

echo ""
