apiVersion: v1
kind: Service
metadata:
  name: {{ include "devbob.fullname" . }}
  labels:
    {{- include "devbob.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.dashboard.dataBridge.enabled }}
    - port: {{ .Values.dashboard.dataBridge.port }}
      targetPort: {{ .Values.dashboard.dataBridge.targetPort }}
      protocol: TCP
      name: data-bridge
    {{- end }}
  selector:
    {{- include "devbob.selectorLabels" . | nindent 4 }}
