{{- if and .Values.istio (eq .Values.istio.enabled true) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "devbob.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devbob.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ include "devbob.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- if .Values.istio.gateway }}
  - {{ .Values.istio.gateway.host | quote }}
  gateways:
  - {{ .Values.istio.gateway.name }}
  {{- end }}
  http:
  - name: devbob-routes
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "devbob.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
      weight: 100
    timeout: 300s
    retries:
      attempts: 3
      perTryTimeout: 100s
      retryOn: 5xx,reset,connect-failure,refused-stream
{{- end }}
