apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabob-{{ .Values.name }}-dry-workers
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      app: metabob-{{ .Values.name }}-worker
      release: {{ .Values.release }}
  template:
    metadata:
      labels:
        app: metabob-{{ .Values.name }}-worker
        version: {{ .Values.image.rpc_api.tag }}
        release: {{ .Values.release }}
    spec:
      containers:
        - name: {{ .Values.name }}-worker
          image: {{ .Values.image.imageRegistry }}/{{ .Values.image.rpc_api.repo }}:{{ .Values.image.rpc_api.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          command: ["celery"]
          args: ["-A", "tasks.jobs", "worker", '-l', 'INFO', "-c", "8"]
          env:
            - name: INSTANCE_PATH
              value: /usr/app
            - name: CONFIG_PATH
              value: /usr/app/.env
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secret-key
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-client
                  key: postgresql-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-client
                  key: postgresql-password
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: universal-config
                  key: JWT_SECRET_KEY
          volumeMounts:
            - mountPath: /usr/app
              name: universal-config
          {{- if .Values.workers.resources }}
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
          {{- else }}
          resources:
            requests:
              memory: "8Gi"
              cpu: "2000m"
          {{- end }}
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - tasks.jobs
                - status
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - tasks.jobs
                - status
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 10
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.config }}
          configMap:
            name: {{ .Values.config }}
            items:
              - key: .env
                path: .env
