{{- if and .Values.istio (eq .Values.istio.enabled true) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: metabob-rpc-api
  namespace: {{ .Values.namespace }}
  labels:
    app: metabob-rpc-api
    release: {{ .Values.release }}
spec:
  hosts:
  - metabob-rpc-api.{{ .Values.namespace }}.svc.cluster.local
  {{- if .Values.istio.gateway }}
  - {{ .Values.istio.gateway.host | quote }}
  gateways:
  - {{ .Values.istio.gateway.name }}
  {{- end }}
  http:
  - name: rpc-api-routes
    match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: metabob-rpc-api.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: 8080
      weight: 100
    timeout: 300s
    retries:
      attempts: 3
      perTryTimeout: 100s
      retryOn: 5xx,reset,connect-failure,refused-stream
{{- end }}
