name: rpc-api
namespace: metabob
release: production

config: "universal-config"

image:
  imageRegistry: metabobapp
  pullPolicy: IfNotPresent
  rpc_api:
    repo: metabob-rpc-api
    tag: 0.12.5

workers:
  replicas: 1

service:
  replicas: 1

surrealdb:
  database: production